name: MSBuild
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Download submodules
      run: git submodule update --init --recursive
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.2
    - name: Install nuget packages
      run: nuget restore ${{ github.workspace }}/gm_turbostroi_win32.sln
    - name: Build
      run: msbuild ${{ github.workspace }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: Release/gmsv_turbostroi_win32.dll
